// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChartController from "./chart_controller"
application.register("chart", ChartController)

import INSSCalculatorController from "./inss_calculator_controller"
application.register("inss-calculator", INSSCalculatorController)
import FlashController from "./flash_controller"
application.register("flash", FlashController)
import nestedFormController from "./nested_form_controller"
application.register("nested-form", nestedFormController)
const { Chart, registerables } = await import('chart.js');
Chart.register(...registerables);