version: '3.8'

services:
  db:
    image: postgres:16.8
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: meu_projeto_rails_development
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
      timeout: 3s

  redis:
    image: redis:7.2
    restart: always

  web:
    build: .
    command: >
      bash -c "
      rm -f tmp/pids/server.pid &&
      until pg_isready -h db -U postgres; do sleep 1; done &&
      echo 'Banco pronto! Iniciando aplicação...' &&
      rails db:migrate &&
      rails db:seed || true &&
      exec rails server -b 0.0.0.0"
    restart: no
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      REDIS_URL: redis://redis:6379/0
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/myapp
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      REDIS_URL: redis://redis:6379/0
    restart: on-failure

volumes:
  postgres_data:
