default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>
  username: <%= ENV.fetch("DATABASE_USER") { "postgres" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "postgres" } %>

development:
  primary: &primary_development
    <<: *default
    database: inss_discount_development
  cache:
    <<: *primary_development
    database: inss_discount_development_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_development
    database: inss_discount_development_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_development
    database: inss_discount_development_cable
    migrations_paths: db/cable_migrate

test:
  <<: *default
  database: inss_discount_test

production:
  primary: &primary_production
    <<: *default
    database: inss_discount_production
    username: inss_discount
    password: <%= ENV["inss_discount_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: inss_discount_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: inss_discount_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: inss_discount_production_cable
    migrations_paths: db/cable_migrate
